#Configuration Email PlaNova Transport
#Sun Feb 22 14:05:02 CET 2026
email.username=houcem.engineering@gmail.com
smtp.port=587
email.password=iyft zvux oxvk zedc
smtp.host=smtp.gmail.com
email.from=PlaNova Transport <houcem.engineering@gmail.com>
