# OAuth Configuration - DO NOT COMMIT TO GITHUB
# This file contains sensitive credentials

# Facebook OAuth Configuration
facebook.app.id=925022893757906
facebook.app.secret=e93e7c5a45f1c523b353a70bdaf5b5b9

# Google OAuth Configuration
google.client.id=342453768411-1go1q6gkb5v15tjls2hgsofq64uhaajh.apps.googleusercontent.com
google.client.secret=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
google.scope=openid email profile
